source 'https://rubygems.org'

gem 'rails', '4.2.1'
gem 'mysql2', '0.3.20'
gem 'sass-rails', '~> 5.0'
gem 'therubyracer', '0.12.2'
gem 'less-rails', '2.7.0'
gem 'twitter-bootstrap-rails', '3.2.0'
gem 'uglifier', '2.7.2'
gem 'coffee-rails', '~> 4.1.0'
gem 'devise', '3.5.2'
gem 'rolify', '4.1.1'
gem 'jquery-ui-rails', '5.0.5'
gem 'jquery-rails', '4.0.4'
gem 'turbolinks', '2.5.3'
gem 'jbuilder', '~> 2.0'
gem 'devise-bootstrap-views', '0.0.6'
gem 'responders', '~> 2.0'
gem 'unicorn', '~> 4.9.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'active_model_serializers', '0.9.3'
gem 'will_paginate', '3.0.7'
gem 'active_model_otp', '1.2.0'
gem 'ckeditor', '~> 4.1.3'
gem 'carrierwave', '~> 0.10.0'
gem 'rmagick', '~> 2.15', '>= 2.15.4'
gem 'ransack'
gem 'axlsx', '~> 2.0', '>= 2.0.1'
gem 'whenever', require: false
gem 'nested_form', '0.3.2'
gem 'gcm', '~> 0.1.0'
gem 'houston', '~> 2.2', '>= 2.2.3'
gem 'will_paginate-bootstrap'
# gem 'sidekiq', '~> 4.0', '>= 4.0.1'
# gem 'sinatra', require: false
# gem 'slim', '~> 3.0', '>= 3.0.6'
gem 'rails_config', '~> 0.4.2'
gem 'sendgrid', '1.2.0'
gem 'payuindia', git: 'git://github.com/payu-india/payuindia.git'
gem 'wicked_pdf', '~> 0.11.0'
gem 'wkhtmltopdf-binary-edge'

group :development, :test do
  gem 'annotate', '2.6.10'
  gem 'byebug', '6.0.2'
  gem 'awesome_print', '1.6.1'
  gem 'rubocop', '0.32.1'
  gem 'pre-commit', '~> 0.24.0'
  gem 'pry', '0.10.1'
  gem 'rspec-rails', '3.3.3'
  gem 'web-console', '~> 2.0'
  gem 'spring', '1.3.6'
end

group :test do
  gem 'factory_girl_rails', '~> 4.5.0'
  gem 'database_cleaner', '1.0.1'
end
