server_name: 'localhost:3000'
gcm_api_key: 'AIzaSyClERKihSuxOJr_DCn-Lu-Zmm1qxdaYTaY'
payu_key: 'gtKFFx'
payu_salt: 'eCwWELxi'
payu_surl: 'http://localhost:3000/payment_success'
payu_furl: 'http://localhost:3000/payment_failure'
payu_url: 'https://test.payu.in/_payment.php'
invitation_url: 'http://bit.ly/1Vk6rst'
app_url: 'http://bit.ly/1PwWnrC'
payu_api: 'https://test.payu.in/merchant/postservice.php?form=2'
paytm_url: 'https://pguat.paytm.com/oltp-web/processTransaction'
paytm_api: 'https://pguat.paytm.com/oltp/HANDLER_INTERNAL/TXNSTATUS?JsonData='
paytm_merchant_key: 'wKc9GanFdAzaEtmp'
website: 'marvelwap'
mid: 'Marvel07749530531173'
industry_type_id: 'Retail'
channel_id: 'WAP'
