server_name: 'mangoes.frools.com'
gcm_api_key: 'AIzaSyClERKihSuxOJr_DCn-Lu-Zmm1qxdaYTaY'
payu_key: '1WEW9I'
payu_salt: 'shkIsBUr'
payu_surl: 'http://mangoes.frools.com/payment_success'
payu_furl: 'http://mangoes.frools.com/payment_failure'
payu_url: 'https://payu.in/_payment.php'
invitation_url: 'http://bit.ly/1PfpW5j'
app_url: 'http://bit.ly/1PwWnrC'
payu_api: 'https://info.payu.in/merchant/postservice.php?form=2'
paytm_url: 'https://secure.paytm.in/oltp-web/processTransaction'
paytm_api: 'https://secure.paytm.com/oltp/HANDLER_INTERNAL/TXNSTATUS?JsonData='
paytm_merchant_key: 'YFyZHzQ#Ey6iINZX'
website: 'marvelwap'
mid: 'marvel09563414808332'
industry_type_id: 'Retail110'
channel_id: 'WEB'
